version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
   environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - AI_MODEL=gemma3:27b
      - CHROMA_HOST=db
      - CHROMA_PORT=8000
    depends_on:
      - db

  db:
    image: chromadb/chroma:0.5.23
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/data
    environment:
      # Tyto proměnné donutí ChromaDB vypnout zbytečnosti a šetřit RAM
      - ANONYMIZED_TELEMETRY=False
      - IS_PERSISTENT=TRUE

volumes:
  chroma_data: